name: small_fsm_example
description: A simple example of how to use the small_fsm package.
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.5.2

# Add regular dependencies here.
dependencies:
  small_fsm:
    path: ../
  logging: ^1.0.0

dev_dependencies:
  lints: ^6.0.0
