name: small_fsm
description: "An easy to use finite state machine implementation using enums for states and events."
version: 1.0.0
repository: https://github.com/kasutu/small_fsm

environment:
  sdk: ^3.0.0

dependencies:
  logging: ^1.0.0

dev_dependencies:
  test: ^1.25.0
  lints: ^6.0.0

flutter:
